name: Build and Push Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Build, tag and push image to ghcr registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v6

      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v4

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DH_USERNAME }}
          password: ${{ secrets.DH_PAT }}

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build local image for vulnerability scanning
        uses: docker/build-push-action@v7
        with:
          context: .
          load: true
          tags: local-scan-image:latest
          cache-from: type=registry,ref=${{ vars.DH_USERNAME }}/${{ vars.DH_REPO }}:buildcache

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'local-scan-image:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ vars.DH_USERNAME }}/${{ vars.DH_REPO }}:buildcache
          cache-to: type=registry,ref=${{ vars.DH_USERNAME }}/${{ vars.DH_REPO }}:buildcache,mode=max
